{
 "title": "Wireguard",
 "description": "Wireguard Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "wg_peer_transfer_tx", "legendFormat": "Total sent" }
   ]
  },
  {
   "title": "Total received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 5, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "(wg_peer_transfer_rx)", "legendFormat": "Total received" }
   ]
  },
  {
   "title": "Throughput",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    { "expr": "irate(wg_peer_transfer_rx[1m])", "legendFormat": "received {{friendly_name}}" },
    {
     "expr": "-irate(wg_peer_transfer_tx[1m])",
     "legendFormat": "sent {{friendly_name}}"
    }
   ]
  },
  {
   "title": "Peer Last Handshake",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "irate(wg_peer_latest_handshake[1m])"
    }
   ]
  },
  {
   "title": "Peer Transmit Bytes Total (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wg_peer_transfer_tx", "legendFormat": "{{allowed_ips}}" }
   ]
  },
  {
   "title": "Peer Receive Bytes Total (1m)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    { "expr": "wg_peer_transfer_rx", "legendFormat": "{{allowed_ips}}" }
   ]
  }
 ]
}